package pdureau:wasm-demo;

interface greeter {
    greet: func(name: string, up: bool, reversed: bool) -> string;
}

interface formatter {
    reverse: func(name: string) -> string;
}

world hello-world-js {
    export greeter;
    import formatter;
}
