package pdureau:wasm-demo;

interface greeter {
    greet: func(name: string, up: bool) -> string;
}

world wasi-cli-rust {
    export wasi:cli/run@0.2.5;
    import wasi:cli/environment@0.2.5;
    import greeter;
}
