spin_manifest_version = 2

[application]
name = "spin-http"
version = "0.1.0"
description = ""

[[trigger.http]]
route = "/..."
component = "spin-http"

[component.spin-http]
source = "../../wasi_http_rust.wasm"
allowed_outbound_hosts = []
